### GET request to example server
GET http://localhost:8080

###

GET http://localhost:8080/software-engineers

###
POST http://localhost:8080/software-engineers
Content-Type: application/json

{
  "name": "John",
  "techStack": "java, springboot"
}

###
GET http://localhost:8080/software-engineers/2